/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package depreciacion;

import javax.swing.JOptionPane;

/**
 *
 * @author ronan
 */
public class Depreciacion extends javax.swing.JFrame {

    /**
     * Creates new form Depreciacion
     */
    public Depreciacion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new java.awt.Panel();
        txtVida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtUnidades = new javax.swing.JTextField();
        txtMensual = new javax.swing.JTextField();
        txtAnual = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnEvaluar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        combTipo = new javax.swing.JComboBox<>();
        txtAquisicion = new javax.swing.JTextField();
        txtResidual = new javax.swing.JTextField();
        combTipo2 = new javax.swing.JComboBox<>();
        txtImporte = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(153, 255, 153));

        txtVida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vida Util Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        txtVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("DEPRECIACIÓN");

        txtUnidades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unidades Producidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        txtUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesActionPerformed(evt);
            }
        });

        txtMensual.setBorder(javax.swing.BorderFactory.createTitledBorder("Depreciacion Mensual"));
        txtMensual.setEnabled(false);
        txtMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensualActionPerformed(evt);
            }
        });

        txtAnual.setBorder(javax.swing.BorderFactory.createTitledBorder("Depreciacion Anual"));
        txtAnual.setEnabled(false);
        txtAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnualActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setText("SALIR");

        btnEvaluar.setBackground(new java.awt.Color(204, 204, 255));
        btnEvaluar.setText("EVALUAR");
        btnEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(204, 204, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        combTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "HORA", "DIA", "MES", "AÑO", "METRO ", "KILOMETRO" }));

        txtAquisicion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor de Aquisicion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        txtAquisicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAquisicionActionPerformed(evt);
            }
        });

        txtResidual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor Residual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        txtResidual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResidualActionPerformed(evt);
            }
        });

        combTipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "HORA", "DIA", "MES", "AÑO", "METRO ", "KILOMETRO" }));

        txtImporte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Importe Depreciable", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 255))); // NOI18N
        txtImporte.setEnabled(false);
        txtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnEvaluar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAquisicion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(txtResidual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(combTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAquisicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResidual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEvaluar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        jLabel1.getAccessibleContext().setAccessibleName("DEPRECIACIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAquisicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAquisicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAquisicionActionPerformed

    private void txtResidualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResidualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResidualActionPerformed

    private void txtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteActionPerformed
        
    }//GEN-LAST:event_txtImporteActionPerformed

    private void txtVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVidaActionPerformed

    private void txtUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesActionPerformed

    private void txtMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensualActionPerformed

    private void txtAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnualActionPerformed

    private void btnEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluarActionPerformed
        try {
            double valorAdquisicion = Double.parseDouble(txtAquisicion.getText());
            double valorResidual = Double.parseDouble(txtResidual.getText());
            double vidaUtil = Double.parseDouble(txtVida.getText());
            double unidadesProducidas = Double.parseDouble(txtUnidades.getText());

            String tipoVidaUtil = combTipo.getSelectedItem().toString();
            String tipoUnidadesProducidas = combTipo2.getSelectedItem().toString();

            // Verificar si los combobox tienen un valor válido seleccionado
            if (tipoVidaUtil.equals("----") || tipoUnidadesProducidas.equals("----")) {
                throw new IllegalArgumentException("Por favor, seleccione unidades válidas.");
            }

            // Asignar categorías a las unidades
            int categoriaVidaUtil = (tipoVidaUtil.equals("HORA") || tipoVidaUtil.equals("DIA") || tipoVidaUtil.equals("MES") || tipoVidaUtil.equals("AÑO")) ? 0 : 1;
            int categoriaUnidadesProducidas = (tipoUnidadesProducidas.equals("HORA") || tipoUnidadesProducidas.equals("DIA") || tipoUnidadesProducidas.equals("MES") || tipoUnidadesProducidas.equals("AÑO")) ? 0 : 1;

            // Verificar si las categorías son diferentes
            if (categoriaVidaUtil != categoriaUnidadesProducidas) {
                throw new IllegalArgumentException("Por favor, seleccione unidades de la misma categoría (tiempo o medida) en ambos ComboBox.");
            }

            double importeDepreciable = valorAdquisicion - valorResidual;
            double depreciacionAnual = 0;
            double depreciacionMensual = 0;

            vidaUtil = convertirUnidad(vidaUtil, tipoVidaUtil, "HORA"); // Convertir vida útil a horas
            unidadesProducidas = convertirUnidad(unidadesProducidas, tipoUnidadesProducidas, "HORA"); // Convertir unidades producidas a horas

            // Calcular depreciación anual y mensual en base a las horas
            if (vidaUtil > 0) {
                depreciacionAnual = importeDepreciable / (vidaUtil / (24 * 365));
                depreciacionMensual = depreciacionAnual / 12;
            } else if (vidaUtil == 0) {
                throw new IllegalArgumentException("Vida útil no puede ser cero.");
            }

            txtImporte.setText(String.valueOf(importeDepreciable));
            txtAnual.setText(String.valueOf(depreciacionAnual));
            txtMensual.setText(String.valueOf(depreciacionMensual));

            JOptionPane.showMessageDialog(this, "Cálculo completado con éxito");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEvaluarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAquisicion.setText("");
        txtResidual.setText("");
        txtImporte.setText("");
        txtVida.setText("");
        txtUnidades.setText("");
        txtMensual.setText("");
        txtAnual.setText("");
        combTipo.setSelectedIndex(0); // Reiniciar el combobox 1
        combTipo2.setSelectedIndex(0); // Reiniciar el combobox 2
    }//GEN-LAST:event_btnLimpiarActionPerformed
private double convertirUnidad(double valor, String tipoOrigen, String tipoDestino) {
    // Conversión de tiempo
    if (tipoOrigen.equals("HORA")) {
        if (tipoDestino.equals("DIA")) {
            return valor / 24;
        } else if (tipoDestino.equals("MES")) {
            return valor / (24 * 30);
        } else if (tipoDestino.equals("AÑO")) {
            return valor / (24 * 365);
        }
    } else if (tipoOrigen.equals("DIA")) {
        if (tipoDestino.equals("HORA")) {
            return valor * 24;
        } else if (tipoDestino.equals("MES")) {
            return valor / 30;
        } else if (tipoDestino.equals("AÑO")) {
            return valor / 365;
        }
    } else if (tipoOrigen.equals("MES")) {
        if (tipoDestino.equals("HORA")) {
            return valor * 24 * 30;
        } else if (tipoDestino.equals("DIA")) {
            return valor * 30;
        } else if (tipoDestino.equals("AÑO")) {
            return valor / 12;
        }
    } else if (tipoOrigen.equals("AÑO")) {
        if (tipoDestino.equals("HORA")) {
            return valor * 24 * 365;
        } else if (tipoDestino.equals("DIA")) {
            return valor * 365;
        } else if (tipoDestino.equals("MES")) {
            return valor * 12;
        }
    }
    // Conversión de distancia
    if (tipoOrigen.equals("METRO")) {
        if (tipoDestino.equals("KILOMETRO")) {
            return valor / 1000;
        }
    } else if (tipoOrigen.equals("KILOMETRO")) {
        if (tipoDestino.equals("METRO")) {
            return valor * 1000;
        }
    }
    return valor;  // Si las unidades son las mismas
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Depreciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Depreciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Depreciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Depreciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Depreciacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combTipo;
    private javax.swing.JComboBox<String> combTipo2;
    private javax.swing.JLabel jLabel1;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtAnual;
    private javax.swing.JTextField txtAquisicion;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtMensual;
    private javax.swing.JTextField txtResidual;
    private javax.swing.JTextField txtUnidades;
    private javax.swing.JTextField txtVida;
    // End of variables declaration//GEN-END:variables
}
